### ISSUE TITLE
[Enhancement] CPU Conservation

### ISSUE THREAD

**Issue by WhiteHalmos** [TooAngel/screeps#118]
Adding thresholds whereby if `config.cpu.conserve` is true, then actions will be gated by their importance and the cpu bucket level.

`
config.cpu = {
  conserve: false,
  high: 9000,
  medium: 6000,
  low: 3000,
  critical: 1000,
}
`

Roles like repairer, scout, and scoutnextroom would only be spawned over high threshold.
Ticks would be skipped below critical.
Autoattack would only commence over high threshold.
Remote rooms would not be reserved or mined if conserve is true.

**Comment by mschultheiss83** [comment]
**Enhancement**
- maybe at medium skip external rooms execution 
- maybe at critical skip my rooms execution or execute
```Memory.myRooms[Game.time % Memory.myRooms.length]```

**Comment by mschultheiss83** [comment]
checkout: https://gist.github.com/mschultheiss83/d25cc6b54cb03934f6007cfbe6bcd1d4
using this main.js for (about 3 days atm), i have now a better income(a factor two or maybe three) on control points per day

for verbose (debug) mode uncomment thie folowing lines
https://gist.github.com/mschultheiss83/d25cc6b54cb03934f6007cfbe6bcd1d4#file-src_main-js-L27 and
https://gist.github.com/mschultheiss83/d25cc6b54cb03934f6007cfbe6bcd1d4#file-src_main-js-L28

**hint: if playing screeps via steam and you uncomment the lines L27+L28** then you will see your current bucket check for about 10 to 15 ticks change to "World" for 5 to 10 minutes, then go back to your main room and check your console again.

> my experience is you save a lot CPU just by changing the view to "World"
JS

**Comment by Nevrdid** [comment]
Not sure about skip totally roles or actions. slow down  or limit can be better.
For example, i seen that for me, i only get out of cpu when i started to manage nextroom. I supose it's because i only have 4 rooms so it's as expensive as it could be later ( tooangel is constantly around 1000 bucket and he looks to manage it good). The main issue i think is that tick skip cause slow down script and it can badly cause some problem if someone is attacking you. Your solution allow to stop to skip for exemple defenser (lower treshold than nextroom management) but you're bucket will still get stuck at nextroom treshold and  all actions which have an highter treshold will still get skiped until you're nextroom is active ( totally skiped, not only slow down).
(Skip repairer while defensing can be a problem, and repairer will only start back when the nextroom become active for have some bucket to use.
I think the ideal solution should be to use more often bucket and cpu limit as argument for action or as dynamic config (e.g role amount).

**Comment by mschultheiss83** [comment]
basic your right it maybe not the best, but i what i see is that i skip one or two ticks than every thing is working for 3 to 5 five ticks than skip one and so on... so having one room exec skipped every five ticks even with someone is attacking me is better before, for me:-)

**Comment by mschultheiss83** [comment]
- see #498 https://github.com/TooAngel/screeps/pull/498/files#diff-cc2bf6eff12695fb4df4b3df6a63a226R17 using sigmoid
- next should be a better creep.handle for these roles: scout, carry, harvester, sourcer
