### ISSUE TITLE
feature/Count-Angels-Alliance-Members-As-Friends?

### ISSUE THREAD

**Issue by Somotaw** [TooAngel/screeps#122]
Is this something we would want? We could probably use the LOAN stuff and make this work if we wanted to.

**Comment by TooAngel** [comment]
Thought about that as well:
I was thinking how can TooAngel AIs verify against each other, also discussing in different channels, couldn't find any way.

I'm thinking about something like building up trust. Not sure which side should trigger it, let's say the one who wants to earn trust.
 - AI messages the other player "Please trust me, give me a task" (can be a saying creep or a controller, ...)
 - If other AI is interested, will start to give tasks: 'Attack that room, kill that creep, don't interrupt my power harvesting, will send a creep to your room, don't attack' .... whatever we come up with
 - With each task solved the other AI gains trust and will be attacked less or even supported

This way the AIs / Alliance can build a some kind of friendship, but dynamic.
If someone else wants to join and is able to solve the tasks it is also fine, they did something for us ...

Get what I mean?

**Comment by Somotaw** [comment]
That would be pretty sweet :D, local config options to be more or less aggressive aswell :)

**Comment by invisioblack** [comment]
Treat it as a game of prisoners dilemma - Score the interactions as such:
Cooperation - Cooperation [Helping each other] + 2
Cooperation - No Cooperation [They Aggress] -4
No Cooperation - No Cooperation [Mutual War] -1
No Cooperation - Cooperation [You Aggress] +4  

everyone starts at like 0 - and positive numbers are friends and negative numbers are enemies?  The values should degrade over large periods of time.

**Comment by Somotaw** [comment]
Hmm interesting, are there any analysis links to this pattern you would like to share?

**Comment by invisioblack** [comment]
There is a feild of study on Cooperation using the prisoners dilemma as the way to evaluate activity.  
https://en.wikipedia.org/wiki/The_Evolution_of_Cooperation
https://en.wikipedia.org/wiki/Prisoner's_dilemma
https://cs.stanford.edu/people/eroberts/courses/soco/projects/1998-99/game-theory/axelrod.html
http://216.119.127.164/edgeware/archive/think/main_filing6.html
http://www.sci.brooklyn.cuny.edu/~sklar/teaching/f05/alife/notes/azhar-ipd-Oct19th.pdf

So using the task idea from above co-operation with each other would be each person completing a task where one person not completing the task would be a 'defect'. Of course we would probably have to have different levels of defecting because not doing a task is not friendly while actively attacking is much less friendly.

The most effective strategy is tit for tat with forgiveness - since this is an environment with 'noise'.

**Comment by mschultheiss83** [comment]
as i read the title i thought, you mean updating src/friends.js and adding all Angels-Alliance-Members.

but the idea is more like feature/dynamic-friends, isn't it?

btw the idea is great!

i would stick to
- a level of friendship - 1 to 8
- a level of foe - 1 to 8

some thoughts:
(1)
- maybe 7 rooms a cross the map i have got a friend (GCL 12), added to src/friends.js, not yet seen by scouts
- some time later friend is in Memory.players, we dont need to check for foe, but do create a level of friendship
- the level of friendship / foe should be calculated by Players GCL (maybe my GCL), so a grater GCL means maybe we can create more complex tasks
  - a foe with higher GCL than myself is maybe not the best idea, maybe expand an other way / room
  - a friend with 22 GCL is more a level 8 friend, a friend with 12 GCL is more a level 4 friend
  - a bonus could be player added to src/friends.js, so i do know the player



some tasks we could maybe add:
- send me some energy to this room terminal if availabe
- send me some resource to that room terminal
- send me at least X amount of Y resource to this Z room.terminal to reach next level of friendship

**Comment by TooAngel** [comment]
So the current status is, we have the `idiot` counter which is something like the foe and we have the reputation which is more the friendship.
Not yet used too much I think this is fine for the beginning.
The Angels alliance does not exist anymore, so I will close this.
