### ISSUE TITLE
W71S66                      getPaths pathStart-harvester missing in cache

### ISSUE THREAD

**Issue by Nevrdid** [TooAngel/screeps#25]
hey, here is another "error" i have since i started, spaming the console. dunno if it's an error because all looks working and actually didn't understand what is the path you're talking about ^^

`getPaths pathStart-5836baa8090e0ab576fdd205 missing in cache
[01:01:32]
W71S66                      getPaths pathStart-W70S66 missing in cache
[01:01:32]
W71S66                      getPaths pathStart-W71S65 missing in cache
[01:01:32]
W71S66                      getPaths pathStart-W71S67 missing in cache
[01:01:32]
W71S66                      getPaths pathStart-filler missing in cache
[01:01:32]
W71S66                      getPaths pathStart-harvester missing in cache
[01:01:53]
W71S66                      getPath pathStart-harvester missing in cache `

**Comment by TooAngel** [comment]
This is a debug message, within the last commits I introduced a room memory cache in global variables.

Store the path in compressed format in memory to reduce the memory footprint. Store the uncompressed path in `global.cache.rooms.NAME`. On fetching the path it is checked if the path is in cache, if not but in Memory, the cache is created and the message is shown.

This happens every time the script is reloaded, either server side or due to a script update. So if you change something the messages will show up. 

https://github.com/TooAngel/screeps/pull/23/commits/7b97b911c0ce19bf7da481c2dff8df817d5ed1f7#diff-2289db94dbbb8d0eef826481d66c4d5bR53 Will remove the debug messages.

**Comment by Nevrdid** [comment]
ok, I will do the modif. But you say it should appear each time i reload script or server reload it but for example, i got this message like +100 times in the last half hour without any modification to the script. Like if path should be calculated/saved but there aren't. It may be better to add a way to activate it if wanted and show debug messages only if it's activate.
Ofc, sorry for talk about nothing if it's planned :)

**Comment by TooAngel** [comment]
Feedback is always good.

Just implemented that feature so bugs are to be expected, maybe I should make it configurable as you suggest. `delete Memory.rooms` is always a good try, reporting of such issues is even better so that I can fix them :-)

**Comment by mschultheiss83** [comment]
by doing so (```delete Memory.rooms```) the spawn or the storage maybe be are in wrong places.

WARNING: you will loose ```Memory.rooms.roomName.position.structure``` and ```Memory.rooms.roomName.walls.ramparts``` and your creeps will build a new base...

**Comment by TooAngel** [comment]
@mschultheiss83 Did it kill any of your structures? When the memory of a room is deleted, the AI starts to recalculate the positions and wall positions. It shouldn't start to interact before every position is set.
The room setup should be deterministic so, the same room layout should be applied.

Let's say I didn't had any issues with that, but could have changed
