### ISSUE TITLE
Scout stuck on border of closed rooms

### ISSUE THREAD

**Issue by Nevrdid** [TooAngel/screeps#27]
If a room is closed, scouts will stay on borders and because the room will never be registered, all next scouts will do the same.

**Comment by WhiteHalmos** [comment]
What does "closed" mean?

**Comment by TooAngel** [comment]
There is (was) a bug on the private server with newly created rooms, where the 'exit definition' was missing. (@WhiteHalmos knows more).
This lead to the situation where the base setup didn't calculated paths to the other rooms, so no ramparts are build. The scout can't leave the room. I guess you a referring to this. If not, tell me.

Maybe if I'm totally bored I will skip scout spawning in this case. I think it is not so much waste of energy and having a scout hanging around it always nice, scouts are really funny guys.

Due to the bug I implemented that the room setup is redone on each RCL change (RCL >= 5), hoping that before RCL 8 the 'exit definition' is fixed and all is working fine.

**Comment by Nevrdid** [comment]
no, i talk about rooms which are close in novice area on official serv.

**Comment by TooAngel** [comment]
Ok, thx, I will not fix that (anytime soon). I think this is a bad idea from the screeps dev to have not working exit tiles. I think it is really tricky to solve the issue and in the end it will solve by itself.

The only thing which I should / will do is making the search path for the scout a bit more random, so that the other exits are also tried.

**Comment by Nevrdid** [comment]
Yeah i understand. Another solution could be to keep one scout on this exit waiting the room opening and avoid others scout to try to go in because there are actually 2 scouts waiting for this room.

**Comment by WhiteHalmos** [comment]
This fixes it for me, kinda: https://github.com/WhiteHalmos/screeps-bot/commit/540e4227ff2280d5f38c7ff13d898a656f90b75e

**Comment by TooAngel** [comment]
> This fixes it for me, kinda: WhiteHalmos@540e422

I like, PR welcome

**Comment by WhiteHalmos** [comment]
Sounds great. Let me clean it up a bit and then make a PR. 😊
