### ISSUE TITLE
[Reminder] AllowRoutingThroughFriendlyRooms does not work.

### ISSUE THREAD

**Issue by totalschaden** [TooAngel/screeps#34]
Not sure why its not working its set to true but its still avoiding the room. If I commend out the Occupied check it works, so its related to the check itself, or my friendsfile ?!

friends.js
module.exports =['abc','defg'];

**Comment by Nevrdid** [comment]
check if you didn't switch accidentaly name to allowRoutingThroughFriendLYRooms. but you shouldn't if you say it work by just commend occupied check... 
can't check myself this evening so : 
`
var friends = require('friends')
.
.
.
if(Memory.rooms[roomName] ){
    let ply= Memory.rooms[roomName].player
    if (Memory.rooms[roomName].state == 'Occupied') {
        console.log('Room occupied');
    }
    if(ply){
        let isFriend = friends.indexOf(ply); // why not friends[ply] or a ply.friends with a proto
        if(isFriend){ 
            console.log('but friendly. Friends : ', friends);
            return 1;
        }
        console.log('Room owner :", ply);
    }
    return Infinity
...
}
`

**Comment by Somotaw** [comment]
I think this can be fixed by editing line 26 in creep_memory_routing.js
should read         if (config.`path`.allowRoutingThroughFriendRooms && friends.indexOf(Memory.rooms[roomName].player) > -1) {

instead of         if (config.allowRoutingThroughFriendRooms && friends.indexOf(Memory.rooms[roomName].player) > -1) {

**Comment by Somotaw** [comment]
Will look into this further
