### ISSUE TITLE
Fresh spawn doesn't get flagged as misplacedSpawn immediately

### ISSUE THREAD

**Issue by sparr** [TooAngel/screeps#442]
I'm not sure when the check happens and the room.memory.misplacedSpawn gets set, but it doesn't appear to be immediately. At least a few creep behaviors change for a misplacedSpawn, so this should be set as soon as possible, right?

**Comment by TooAngel** [comment]
It is set here: https://github.com/TooAngel/screeps/blob/21148c86b70acb761393522c9eae598808a14142/src/prototype_room_basebuilder.js#L98

The AI checks regularly if structures are at the wrong position, when it checks the spawn, it sets it to `misplaced`.

Earlier is surely better, for changing also the cases needs to be considered e.g. if the layout changes due to code changes.
