### ISSUE TITLE
Add ramparts on key structures

### ISSUE THREAD

**Issue by WhiteHalmos** [TooAngel/screeps#74]
Spawns and especially towers need ramparts on them in order to be effective. Towers are most effective at close range.

**Comment by mschultheiss83** [comment]
atm: i added ramparts manuel by 
```
// replace roomName + i for spawn
Memory.rooms['roomName'].walls.ramparts.push(Memory.rooms['roomName'].position.structure.spawn[i]);
```

**Comment by TooAngel** [comment]
Configurable and I'm fine with it.

My 3 cents: I considered a room as lost as soon as the outer wall is broken. If you manage to get into the room you can destroy so much of the economy that the rest will anyway fall, sooner or later.

Other consideration are nukes. Building ramparts on a nuke attack is already implemented, but is in most of cases too slow for the current nuke damage.

So my thought approach is to have a proper mineral handling and being able to build up the ramparts fast enough.

E.g. Dissi moves his towers to the exits where the attacker is coming from. So ramparts would be a waste of energy.

**Comment by WhiteHalmos** [comment]
Good point, perhaps adding logic to move structures temporarily (especially towers) would be best. i.e. if a nuke comes in on the spawns, move them instead of wasting energy on ramparts. Only things that can't move easily like storage and terminal should get nuke protection. WDYT?

**Comment by TooAngel** [comment]
Who says I can't move a storage or a terminal, by dropping and wasting resources, did that a couple of times ;-)

I think I would take the approach:
 1. Build ramparts on tricky moveable structures, like terminal and storage (maybe a config for that)
 2. Build ramparts on important structures, spawns and towers (if I'm still in the mood, with a different config). Build ramparts on spawns doesn't work so well currently and we don't move towers currently.
 
Instead of working on step two, the existing nuke logic could be improved, too. Or looking into the tower movement. Or spawn moving logic.
Even thou I think step 2 is not necessary the best (IMHO, could be wrong), it could be good to have it. So that different accounts could have different configs, so it is not so easy recognizable if it is a TooAngel AI or even to test what is the best solution.
